// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthButton: typeof import('./src/components/AuthButton.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    'IMaterialSymbols:arrowBack': typeof import('~icons/material-symbols/arrow-back')['default']
    'IMaterialSymbols:home': typeof import('~icons/material-symbols/home')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    'IZondicons:indentDecrease': typeof import('~icons/zondicons/indent-decrease')['default']
    'IZondicons:indentIncrease': typeof import('~icons/zondicons/indent-increase')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
